#!/usr/bin/env bash
# TRIM setup script
#
# Usage:
#   ./setup.sh                              # start Podman container
#   ./setup.sh --install /path/to/project  # wire hooks into a project (HTTP mode)
#   ./setup.sh --local --install /path     # wire hooks using local subprocess (no container)
#   ./setup.sh --uninstall /path           # remove hooks from a project

set -euo pipefail

TRIM_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKER_URL="${WORKER_URL:-http://localhost:8080}"
MODE="http"
INSTALL_DIR=""
UNINSTALL_DIR=""

# ── Parse args ────────────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
    case $1 in
        --install)   INSTALL_DIR="$2"; shift 2 ;;
        --uninstall) UNINSTALL_DIR="$2"; shift 2 ;;
        --local)     MODE="subprocess"; shift ;;
        --url)       WORKER_URL="$2"; shift 2 ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

# ── Uninstall ─────────────────────────────────────────────────────────────────
if [[ -n "$UNINSTALL_DIR" ]]; then
    echo "Removing TRIM hooks from $UNINSTALL_DIR ..."
    rm -f "$UNINSTALL_DIR/.claude/hooks/trim-check-file-size.sh"
    rm -f "$UNINSTALL_DIR/.claude/hooks/trim-check-bash-read.sh"

    SETTINGS="$UNINSTALL_DIR/.claude/settings.json"
    if [[ -f "$SETTINGS" ]]; then
        # Pass path via argv — no shell embedding
        python3 - "$SETTINGS" << 'PYEOF'
import json, sys
settings_path = sys.argv[1]
with open(settings_path) as f:
    d = json.load(f)
hooks = d.get('hooks', {}).get('PreToolUse', [])
hooks = [h for h in hooks if 'trim-check' not in str(h.get('hooks', ''))]
d.setdefault('hooks', {})['PreToolUse'] = hooks
with open(settings_path, 'w') as f:
    json.dump(d, f, indent=2)
print('Patched settings.json')
PYEOF
    fi
    echo "Done. TRIM hooks removed."
    exit 0
fi

# ── Container-only (no --install) ─────────────────────────────────────────────
if [[ -z "$INSTALL_DIR" ]]; then
    echo "Starting TRIM worker container..."
    podman-compose up -d
    echo ""
    echo "Worker running at $WORKER_URL"
    echo "Health check:"
    sleep 2
    curl -sf "$WORKER_URL/health" && echo "" \
        || echo "  (container may still be starting — try: curl $WORKER_URL/health)"
    echo ""
    echo "To wire TRIM into a project, run:"
    echo "  ./setup.sh --install /path/to/your/project"
    exit 0
fi

# ── Install hooks into target project ─────────────────────────────────────────
TARGET="$(cd "$INSTALL_DIR" && pwd)"
HOOKS_DIR="$TARGET/.claude/hooks"
SETTINGS="$TARGET/.claude/settings.json"

mkdir -p "$HOOKS_DIR"

echo "Installing TRIM hooks into $TARGET ..."
echo "Mode: $MODE"

if [[ "$MODE" == "http" ]]; then
    # ── HTTP mode: generated hooks use only curl + python3 (no TRIM venv) ────
    # WORKER_URL is baked into the generated script at install time.

    cat > "$HOOKS_DIR/trim-check-file-size.sh" << HOOK
#!/usr/bin/env bash
# TRIM — PreToolUse hook for Read tool (HTTP mode)
# Auto-generated by setup.sh — worker: ${WORKER_URL}
set -euo pipefail

TRIM_WORKER="${WORKER_URL}"
MIN_LINES="\${SHUNT_MIN_LINES:-350}"
MAX_BYTES="\${SHUNT_MAX_BYTES:-400000}"
TRIM_API_KEY="\${TRIM_API_KEY:-}"

HOOK_JSON="\$(cat)"

FILE_PATH="\$(echo "\$HOOK_JSON" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('tool_input',{}).get('file_path',''))")" || exit 0
OFFSET="\$(echo "\$HOOK_JSON"   | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('tool_input',{}).get('offset',''))")"   || exit 0
LIMIT="\$(echo "\$HOOK_JSON"    | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('tool_input',{}).get('limit',''))")"    || exit 0

[[ -z "\$FILE_PATH" || ! -f "\$FILE_PATH" ]] && exit 0
[[ -n "\$OFFSET" || -n "\$LIMIT" ]] && exit 0

LINE_COUNT="\$(wc -l < "\$FILE_PATH" | tr -d ' ')" || exit 0
BYTE_COUNT="\$(wc -c < "\$FILE_PATH" | tr -d ' ')" || exit 0

(( LINE_COUNT < MIN_LINES )) && exit 0
(( BYTE_COUNT > MAX_BYTES )) && exit 0

# Python reads the file directly — safe path handling, no shell quoting issues
PAYLOAD="\$(python3 -c "
import json, sys
fp = sys.argv[1]
with open(fp, encoding='utf-8', errors='replace') as f:
    content = f.read()
print(json.dumps({'file_path': fp, 'content': content}))
" "\$FILE_PATH")" || exit 0

AUTH_HEADER=""
[[ -n "\$TRIM_API_KEY" ]] && AUTH_HEADER="-H X-TRIM-Key:\${TRIM_API_KEY}"

# shellcheck disable=SC2086
RESPONSE="\$(echo "\$PAYLOAD" | curl -sf \
    -X POST "\${TRIM_WORKER}/bulk-read" \
    -H 'Content-Type: application/json' \
    --data-binary @- \
    \${AUTH_HEADER:+"\$AUTH_HEADER"} \
    --max-time "\${SHUNT_TIMEOUT_SECONDS:-45}" 2>/dev/null)" || exit 0

SUMMARY="\$(echo "\$RESPONSE" | python3 -c "import json,sys; print(json.loads(sys.stdin.read()).get('summary',''))")" || exit 0
[[ -z "\$SUMMARY" ]] && exit 0

python3 -c "
import json, sys
summary, fp, lc = sys.argv[1], sys.argv[2], sys.argv[3]
context = (
    f'[TRIM] Delegated read of {fp} ({lc} lines) to cheap LLM.\n'
    f'Summary:\n{summary}\n\n'
    f'(Full file was NOT loaded — use this summary to answer the question.)'
)
print(json.dumps({
    'hookSpecificOutput': {'permissionDecision': 'deny'},
    'additionalContext': context,
}))
" "\$SUMMARY" "\$FILE_PATH" "\$LINE_COUNT"
HOOK

    cat > "$HOOKS_DIR/trim-check-bash-read.sh" << HOOK
#!/usr/bin/env bash
# TRIM — PreToolUse hook for Bash tool (HTTP mode)
# Auto-generated by setup.sh — worker: ${WORKER_URL}
set -euo pipefail

TRIM_WORKER="${WORKER_URL}"
MIN_LINES="\${SHUNT_MIN_LINES:-350}"
MAX_BYTES="\${SHUNT_MAX_BYTES:-400000}"
TRIM_API_KEY="\${TRIM_API_KEY:-}"

HOOK_JSON="\$(cat)"
COMMAND="\$(echo "\$HOOK_JSON" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('tool_input',{}).get('command',''))")" || exit 0
[[ -z "\$COMMAND" ]] && exit 0

FILE_PATH="\$(python3 - "\$COMMAND" << 'PYEOF'
import re, sys
cmd = sys.argv[1]
if '|' in cmd or '>' in cmd or '<' in cmd: sys.exit(1)
m = re.match(r'^(cat|head|tail|less|more)\s+(?:-\S+\s+)*(\S+)$', cmd.strip())
if not m: sys.exit(1)
fp = m.group(2)
if '*' in fp or '?' in fp: sys.exit(1)
print(fp)
PYEOF
)" || exit 0

[[ -z "\$FILE_PATH" || ! -f "\$FILE_PATH" ]] && exit 0

LINE_COUNT="\$(wc -l < "\$FILE_PATH" | tr -d ' ')" || exit 0
BYTE_COUNT="\$(wc -c < "\$FILE_PATH" | tr -d ' ')" || exit 0

(( LINE_COUNT < MIN_LINES )) && exit 0
(( BYTE_COUNT > MAX_BYTES )) && exit 0

PAYLOAD="\$(python3 -c "
import json, sys
fp = sys.argv[1]
with open(fp, encoding='utf-8', errors='replace') as f:
    content = f.read()
print(json.dumps({'file_path': fp, 'content': content}))
" "\$FILE_PATH")" || exit 0

AUTH_HEADER=""
[[ -n "\$TRIM_API_KEY" ]] && AUTH_HEADER="-H X-TRIM-Key:\${TRIM_API_KEY}"

# shellcheck disable=SC2086
RESPONSE="\$(echo "\$PAYLOAD" | curl -sf \
    -X POST "\${TRIM_WORKER}/bulk-read" \
    -H 'Content-Type: application/json' \
    --data-binary @- \
    \${AUTH_HEADER:+"\$AUTH_HEADER"} \
    --max-time "\${SHUNT_TIMEOUT_SECONDS:-45}" 2>/dev/null)" || exit 0

SUMMARY="\$(echo "\$RESPONSE" | python3 -c "import json,sys; print(json.loads(sys.stdin.read()).get('summary',''))")" || exit 0
[[ -z "\$SUMMARY" ]] && exit 0

python3 -c "
import json, sys
summary, fp, lc = sys.argv[1], sys.argv[2], sys.argv[3]
context = (
    f'[TRIM] Delegated bash read of {fp} ({lc} lines) to cheap LLM.\n'
    f'Summary:\n{summary}\n\n'
    f'(Full file was NOT loaded — use this summary to answer the question.)'
)
print(json.dumps({
    'hookSpecificOutput': {'permissionDecision': 'deny'},
    'additionalContext': context,
}))
" "\$SUMMARY" "\$FILE_PATH" "\$LINE_COUNT"
HOOK

else
    # ── Subprocess mode: copy TRIM hooks, hardcode PROJECT_ROOT path ──────────
    PYTHON="$TRIM_DIR/.venv/bin/python"
    if [[ ! -x "$PYTHON" ]]; then
        echo "Error: venv not found at $TRIM_DIR/.venv"
        echo "Run: python3 -m venv .venv && .venv/bin/pip install -r requirements.txt"
        exit 1
    fi

    # Use python to do the substitution safely — avoids sed delimiter conflicts
    # when TRIM_DIR contains special characters
    python3 - "$TRIM_DIR" \
              "$TRIM_DIR/.claude/hooks/check-file-size.sh" \
              "$HOOKS_DIR/trim-check-file-size.sh" << 'PYEOF'
import sys
trim_dir, src, dst = sys.argv[1], sys.argv[2], sys.argv[3]
with open(src) as f:
    content = f.read()
# Replace the dynamic PROJECT_ROOT detection with the absolute TRIM path
content = content.replace(
    'PROJECT_ROOT="$(dirname "$(dirname "$SCRIPT_DIR")")"',
    f'PROJECT_ROOT="{trim_dir}"',
    1,
)
with open(dst, 'w') as f:
    f.write(content)
PYEOF

    python3 - "$TRIM_DIR" \
              "$TRIM_DIR/.claude/hooks/check-bash-read.sh" \
              "$HOOKS_DIR/trim-check-bash-read.sh" << 'PYEOF'
import sys
trim_dir, src, dst = sys.argv[1], sys.argv[2], sys.argv[3]
with open(src) as f:
    content = f.read()
content = content.replace(
    'PROJECT_ROOT="$(dirname "$(dirname "$SCRIPT_DIR")")"',
    f'PROJECT_ROOT="{trim_dir}"',
    1,
)
with open(dst, 'w') as f:
    f.write(content)
PYEOF

fi

chmod +x "$HOOKS_DIR/trim-check-file-size.sh" "$HOOKS_DIR/trim-check-bash-read.sh"

# ── Patch target project's .claude/settings.json ─────────────────────────────
python3 - "$SETTINGS" << 'PYEOF'
import json, sys, os

settings_path = sys.argv[1]
os.makedirs(os.path.dirname(settings_path), exist_ok=True)

if os.path.exists(settings_path):
    with open(settings_path) as f:
        d = json.load(f)
else:
    d = {}

d.setdefault("hooks", {}).setdefault("PreToolUse", [])
hooks = d["hooks"]["PreToolUse"]

# Remove any existing TRIM entries to avoid duplicates
hooks = [h for h in hooks if "trim-check" not in str(h.get("hooks", ""))]

hooks += [
    {
        "matcher": "Read",
        "hooks": [{"type": "command", "command": "/bin/bash .claude/hooks/trim-check-file-size.sh"}],
    },
    {
        "matcher": "Bash",
        "hooks": [{"type": "command", "command": "/bin/bash .claude/hooks/trim-check-bash-read.sh"}],
    },
]

d["hooks"]["PreToolUse"] = hooks

with open(settings_path, "w") as f:
    json.dump(d, f, indent=2)

print(f"Patched {settings_path}")
PYEOF

echo ""
echo "TRIM installed into $TARGET"
echo ""
echo "  Hooks:    $HOOKS_DIR/trim-check-*.sh"
echo "  Settings: $SETTINGS"
if [[ "$MODE" == "http" ]]; then
    echo "  Worker:   $WORKER_URL"
    echo ""
    echo "Make sure the TRIM container is running:"
    echo "  cd $TRIM_DIR && podman-compose up -d"
fi
echo ""
echo "Open Claude Code in $TARGET — large file reads are now routed through TRIM."
