#!/usr/bin/env bash
# TRIM setup script
#
# Usage:
#   ./setup.sh                              # start Podman container
#   ./setup.sh --install /path/to/project  # wire hooks into a project (HTTP mode)
#   ./setup.sh --local --install /path     # wire hooks using local subprocess (no container)
#   ./setup.sh --uninstall /path           # remove hooks from a project

set -euo pipefail

TRIM_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKER_URL="${WORKER_URL:-http://localhost:8080}"
MODE="http"
INSTALL_DIR=""
UNINSTALL_DIR=""

# ── Parse args ────────────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
    case $1 in
        --install)   INSTALL_DIR="$2"; shift 2 ;;
        --uninstall) UNINSTALL_DIR="$2"; shift 2 ;;
        --local)     MODE="subprocess"; shift ;;
        --url)       WORKER_URL="$2"; shift 2 ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

# ── Uninstall ─────────────────────────────────────────────────────────────────
if [[ -n "$UNINSTALL_DIR" ]]; then
    echo "Removing TRIM hooks from $UNINSTALL_DIR ..."
    rm -f "$UNINSTALL_DIR/.claude/hooks/trim-check-file-size.sh"
    rm -f "$UNINSTALL_DIR/.claude/hooks/trim-check-bash-read.sh"

    SETTINGS="$UNINSTALL_DIR/.claude/settings.json"
    if [[ -f "$SETTINGS" ]]; then
        python3 -c "
import json, sys
with open('$SETTINGS') as f:
    d = json.load(f)
hooks = d.get('hooks', {}).get('PreToolUse', [])
hooks = [h for h in hooks if 'trim-check' not in str(h.get('hooks', ''))]
d.setdefault('hooks', {})['PreToolUse'] = hooks
with open('$SETTINGS', 'w') as f:
    json.dump(d, f, indent=2)
print('Patched settings.json')
"
    fi
    echo "Done. TRIM hooks removed."
    exit 0
fi

# ── Container-only (no --install) ─────────────────────────────────────────────
if [[ -z "$INSTALL_DIR" ]]; then
    echo "Starting TRIM worker container..."
    podman-compose up -d
    echo ""
    echo "Worker running at $WORKER_URL"
    echo "Health check:"
    sleep 2
    curl -sf "$WORKER_URL/health" && echo "" || echo "  (container may still be starting — try: curl $WORKER_URL/health)"
    echo ""
    echo "To wire TRIM into a project, run:"
    echo "  ./setup.sh --install /path/to/your/project"
    exit 0
fi

# ── Install hooks into target project ─────────────────────────────────────────
TARGET="$(cd "$INSTALL_DIR" && pwd)"
HOOKS_DIR="$TARGET/.claude/hooks"
SETTINGS="$TARGET/.claude/settings.json"

mkdir -p "$HOOKS_DIR"

echo "Installing TRIM hooks into $TARGET ..."
echo "Mode: $MODE"

if [[ "$MODE" == "http" ]]; then
    # ── HTTP mode: hooks only need curl + jq, no Python on host ──────────────

    cat > "$HOOKS_DIR/trim-check-file-size.sh" << HOOK
#!/usr/bin/env bash
# TRIM — PreToolUse hook for Read tool (HTTP mode)
# Auto-generated by setup.sh — do not edit manually
set -euo pipefail

TRIM_WORKER="${WORKER_URL}"
MIN_LINES="\${SHUNT_MIN_LINES:-350}"
MAX_BYTES="\${SHUNT_MAX_BYTES:-400000}"

HOOK_JSON="\$(cat)"

FILE_PATH="\$(echo "\$HOOK_JSON" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('tool_input',{}).get('file_path',''))")"
OFFSET="\$(echo "\$HOOK_JSON" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('tool_input',{}).get('offset',''))")"
LIMIT="\$(echo "\$HOOK_JSON" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('tool_input',{}).get('limit',''))")"

[[ -z "\$FILE_PATH" || ! -f "\$FILE_PATH" ]] && exit 0
[[ -n "\$OFFSET" || -n "\$LIMIT" ]] && exit 0

LINE_COUNT="\$(wc -l < "\$FILE_PATH" | tr -d ' ')"
BYTE_COUNT="\$(wc -c < "\$FILE_PATH" | tr -d ' ')"

(( LINE_COUNT < MIN_LINES )) && exit 0
(( BYTE_COUNT > MAX_BYTES )) && exit 0

CONTENT="\$(cat "\$FILE_PATH")"
PAYLOAD="\$(python3 -c "import json,sys; print(json.dumps({'file_path': sys.argv[1], 'content': sys.argv[2]}))" "\$FILE_PATH" "\$CONTENT")"

RESPONSE="\$(curl -sf -X POST "\${TRIM_WORKER}/bulk-read" \
    -H 'Content-Type: application/json' \
    -d "\$PAYLOAD" \
    --max-time "\${SHUNT_TIMEOUT_SECONDS:-45}" 2>/dev/null)" || exit 0

SUMMARY="\$(echo "\$RESPONSE" | python3 -c "import json,sys; print(json.loads(sys.stdin.read()).get('summary',''))")"
[[ -z "\$SUMMARY" ]] && exit 0

python3 -c "
import json, sys
summary, fp, lc = sys.argv[1], sys.argv[2], sys.argv[3]
print(json.dumps({
    'hookSpecificOutput': {'permissionDecision': 'allow'},
    'additionalContext': f'[TRIM] Delegated read of {fp} ({lc} lines) to cheap LLM.\nSummary:\n{summary}\n(Full file NOT loaded into context.)',
    'suppressToolUse': True,
}))
" "\$SUMMARY" "\$FILE_PATH" "\$LINE_COUNT"
HOOK

    cat > "$HOOKS_DIR/trim-check-bash-read.sh" << HOOK
#!/usr/bin/env bash
# TRIM — PreToolUse hook for Bash tool (HTTP mode)
# Auto-generated by setup.sh — do not edit manually
set -euo pipefail

TRIM_WORKER="${WORKER_URL}"
MIN_LINES="\${SHUNT_MIN_LINES:-350}"
MAX_BYTES="\${SHUNT_MAX_BYTES:-400000}"

HOOK_JSON="\$(cat)"
COMMAND="\$(echo "\$HOOK_JSON" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('tool_input',{}).get('command',''))")"

[[ -z "\$COMMAND" ]] && exit 0

FILE_PATH="\$(python3 - "\$COMMAND" << 'EOF'
import re, sys
cmd = sys.argv[1]
if '|' in cmd or '>' in cmd or '<' in cmd: sys.exit(1)
m = re.match(r'^(cat|head|tail|less|more)\s+(?:-\S+\s+)*(\S+)$', cmd.strip())
if not m: sys.exit(1)
fp = m.group(2)
if '*' in fp or '?' in fp: sys.exit(1)
print(fp)
EOF
)" || exit 0

[[ -z "\$FILE_PATH" || ! -f "\$FILE_PATH" ]] && exit 0

LINE_COUNT="\$(wc -l < "\$FILE_PATH" | tr -d ' ')"
BYTE_COUNT="\$(wc -c < "\$FILE_PATH" | tr -d ' ')"

(( LINE_COUNT < MIN_LINES )) && exit 0
(( BYTE_COUNT > MAX_BYTES )) && exit 0

CONTENT="\$(cat "\$FILE_PATH")"
PAYLOAD="\$(python3 -c "import json,sys; print(json.dumps({'file_path': sys.argv[1], 'content': sys.argv[2]}))" "\$FILE_PATH" "\$CONTENT")"

RESPONSE="\$(curl -sf -X POST "\${TRIM_WORKER}/bulk-read" \
    -H 'Content-Type: application/json' \
    -d "\$PAYLOAD" \
    --max-time "\${SHUNT_TIMEOUT_SECONDS:-45}" 2>/dev/null)" || exit 0

SUMMARY="\$(echo "\$RESPONSE" | python3 -c "import json,sys; print(json.loads(sys.stdin.read()).get('summary',''))")"
[[ -z "\$SUMMARY" ]] && exit 0

python3 -c "
import json, sys
summary, fp, lc = sys.argv[1], sys.argv[2], sys.argv[3]
print(json.dumps({
    'hookSpecificOutput': {'permissionDecision': 'allow'},
    'additionalContext': f'[TRIM] Delegated bash read of {fp} ({lc} lines) to cheap LLM.\nSummary:\n{summary}\n(Full file NOT loaded into context.)',
    'suppressToolUse': True,
}))
" "\$SUMMARY" "\$FILE_PATH" "\$LINE_COUNT"
HOOK

else
    # ── Subprocess mode: copy TRIM's own hooks, inject TRIM path ─────────────
    PYTHON="$TRIM_DIR/.venv/bin/python"
    if [[ ! -x "$PYTHON" ]]; then
        echo "Error: venv not found at $TRIM_DIR/.venv"
        echo "Run: python3 -m venv .venv && .venv/bin/pip install -r requirements.txt"
        exit 1
    fi

    # Copy and patch hooks with absolute TRIM_DIR
    sed "s|PROJECT_ROOT=\"\$(dirname \"\$(dirname \"\$SCRIPT_DIR\")\")\"|\PROJECT_ROOT=\"$TRIM_DIR\"|g" \
        "$TRIM_DIR/.claude/hooks/check-file-size.sh" > "$HOOKS_DIR/trim-check-file-size.sh"
    sed "s|PROJECT_ROOT=\"\$(dirname \"\$(dirname \"\$SCRIPT_DIR\")\")\"|\PROJECT_ROOT=\"$TRIM_DIR\"|g" \
        "$TRIM_DIR/.claude/hooks/check-bash-read.sh" > "$HOOKS_DIR/trim-check-bash-read.sh"
fi

chmod +x "$HOOKS_DIR/trim-check-file-size.sh" "$HOOKS_DIR/trim-check-bash-read.sh"

# ── Patch target project's .claude/settings.json ─────────────────────────────
python3 - "$SETTINGS" << 'EOF'
import json, sys, os

settings_path = sys.argv[1]
os.makedirs(os.path.dirname(settings_path), exist_ok=True)

if os.path.exists(settings_path):
    with open(settings_path) as f:
        d = json.load(f)
else:
    d = {}

d.setdefault("hooks", {}).setdefault("PreToolUse", [])

hooks = d["hooks"]["PreToolUse"]

# Remove any existing TRIM entries to avoid duplicates
hooks = [h for h in hooks if "trim-check" not in str(h.get("hooks", ""))]

hooks += [
    {
        "matcher": "Read",
        "hooks": [{"type": "command", "command": "/bin/bash .claude/hooks/trim-check-file-size.sh"}]
    },
    {
        "matcher": "Bash",
        "hooks": [{"type": "command", "command": "/bin/bash .claude/hooks/trim-check-bash-read.sh"}]
    }
]

d["hooks"]["PreToolUse"] = hooks

with open(settings_path, "w") as f:
    json.dump(d, f, indent=2)

print(f"Patched {settings_path}")
EOF

echo ""
echo "TRIM installed into $TARGET"
echo ""
echo "  Hooks:    $HOOKS_DIR/trim-check-*.sh"
echo "  Settings: $SETTINGS"
if [[ "$MODE" == "http" ]]; then
echo "  Worker:   $WORKER_URL"
echo ""
echo "Make sure the TRIM container is running:"
echo "  cd $TRIM_DIR && podman-compose up -d"
fi
echo ""
echo "Open Claude Code in $TARGET — large file reads are now routed through TRIM."
